const $=s=>document.querySelector(s),api="/api";let active="hospital";
const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"}[c]));
async function get(url){const r=await fetch(api+url);if(!r.ok)throw Error();return r.json()}
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),3500)}
async function overview(){try{const d=await get("/overview"),x=[[d.hospitals,"Care hospitals"],[d.doctors,"Specialist doctors"],[d.cancer_types,"Cancer guides"],[d.stories,"Community stories"]];$("#stats").innerHTML=x.map(a=>`<div><b>${a[0]}+</b><span>${a[1]}</span></div>`).join("")}catch{}}
function hospitalCards(x){return x.length?x.slice(0,4).map(h=>`<button class="result" data-hospital="${h.hospital_id}"><i>✦</i><span><b>${esc(h.hospital_name)}</b><small>${esc(h.area)}, ${esc(h.district)} · ${esc(h.hospital_type)}</small></span><strong>→</strong></button>`).join(""):`<p>No hospitals match your search. Try another area.</p>`}
function doctorCards(x){return x.length?x.slice(0,4).map(d=>`<article class="result doctor-result"><i>${esc(d.doctor_name[0])}</i><span><b>Dr. ${esc(d.doctor_name)}</b><small>${esc(d.specialties)} · ${esc(d.area)}</small></span><strong>${d.experience_years||""}${d.experience_years?" yrs":""}</strong></article>`).join(""):`<p>No doctors match your search. Try another name or area.</p>`}
async function directory(q=""){const el=$("#directoryResults");el.innerHTML="<p>Finding care options…</p>";try{const x=await get(`/${active==="hospital"?"hospitals":"doctors"}?search=${encodeURIComponent(q)}`);el.innerHTML=active==="hospital"?hospitalCards(x):doctorCards(x)}catch{el.innerHTML="<p>We could not reach the care directory. Ensure the server and database are running.</p>"}}
async function guides(){try{const x=await get("/cancers"),sym=["◌","✦","◈","♡"];$("#guideGrid").innerHTML=x.slice(0,6).map((g,i)=>`<article class="guide"><i class="g${i%4}">${sym[i%4]}</i><div><small>UNDERSTANDING CANCER</small><h3>${esc(g.cancer_name)}</h3><p>${esc(g.causes||"Learn about this cancer type and prepare for care.")}</p><a href="#care">Explore guide →</a></div></article>`).join("")}catch{$("#guideGrid").innerHTML="<p>Guides will appear once the database is connected.</p>"}}
async function stories(){try{const x=await get("/blogs");$("#storyGrid").innerHTML=x.map((s,i)=>`<article class="story"><div class="story-head s${i}">${["“","✦","♡"][i]}</div><div><small>COMMUNITY STORY</small><h3>${esc(s.title)}</h3><p>${esc((s.feel||"A reflection from the CancerCare community.").slice(0,155))}</p><a href="#stories">Read story →</a></div></article>`).join("")}catch{$("#storyGrid").innerHTML="<p>Stories will appear once the database is connected.</p>"}}
async function hospital(id){const d=$("#detailDialog"),c=$("#detailContent");d.showModal();c.innerHTML="<p>Loading hospital details…</p>";try{const h=await get(`/hospitals/${id}`);c.innerHTML=`<p class="eyebrow">— &nbsp; HOSPITAL PROFILE</p><h2>${esc(h.hospital_name)}</h2><p class="muted">${esc(h.hospital_type)} hospital · ${esc(h.area)}, ${esc(h.district)}</p><div class="details"><div><small>ADDRESS</small><p>${esc(h.address)}</p></div><div><small>CONTACT</small><p>${esc(h.phone)}<br>${esc(h.email||"Contact hospital directly")}</p></div><div><small>CAPACITY</small><p>${esc(h.bed_capacity)} beds</p></div><div><small>ESTABLISHED</small><p>${esc(h.established_year)}</p></div></div>${h.website?`<a class="button" target="_blank" rel="noopener" href="${esc(h.website)}">Visit hospital website ↗</a>`:""}`}catch{c.innerHTML="<h2>Hospital details unavailable</h2><p>Please try again in a moment.</p>"}}
$("#openLogin").onclick=()=>$("#loginDialog").showModal();document.querySelectorAll(".close").forEach(b=>b.onclick=()=>b.closest("dialog").close());document.querySelectorAll("[data-role]").forEach(b=>b.onclick=()=>{ $("#loginDialog").close();toast(`${b.dataset.role} access is managed by your hospital care team.`)});document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{active=b.dataset.search;document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("active",x===b));$("#directorySearch").placeholder=active==="hospital"?"Search by hospital name or area":"Search doctor name or area";directory($("#directorySearch").value)});$("#searchButton").onclick=()=>directory($("#directorySearch").value);$("#directorySearch").onkeydown=e=>e.key==="Enter"&&directory(e.target.value);$("#directoryResults").onclick=e=>{const x=e.target.closest("[data-hospital]");if(x)hospital(x.dataset.hospital)};$(".menu").onclick=()=>$(".links").classList.toggle("show");overview();directory();guides();stories();
